version: '3.2'
#========================================
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ft_db
    tty: true # 나중에 지울 것.
    expose:
      - "5432"
    volumes:
      - type: bind
        source: ./table.sql
        target: /docker-entrypoint-initdb.d/table.sql
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    networks:
      - intra
  nest:
    container_name: nest
    build: ./backend
    ports:
      - "3000:3000"
      - "8000:8000"
      - "4242:4242"
    depends_on:
      - react
      - postgres
    tty: true
    networks:
      - intra
    volumes:
      - type: bind
        source: ./uploads
        target: /app/uploads

  react:
    container_name: react
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    tty: true
    networks:
      - intra
volumes:
  db_volume:
networks:
  intra:
    driver: bridge
#========================================
